USE [MTWIN]
GO

/****** Object:  Table [dbo].[分類項目]    Script Date: 05/28/2015 03:36:23 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[分類項目](
	[分類Id] [int] IDENTITY(1,1) NOT NULL,
	[分類名稱] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_分類項目] PRIMARY KEY CLUSTERED 
(
	[分類Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

