//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTWIN.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MTWINEntities : DbContext
    {
        public MTWINEntities()
            : base("name=MTWINEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<店家登錄> 店家登錄 { get; set; }
        public virtual DbSet<首頁項目> 首頁項目 { get; set; }
        public virtual DbSet<推薦店家> 推薦店家 { get; set; }
        public virtual DbSet<首頁項目分類> 首頁項目分類 { get; set; }
        public virtual DbSet<推薦店家分類> 推薦店家分類 { get; set; }
    }
}
