//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTWIN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 分類項目
    {
        public 分類項目()
        {
            this.推薦店家 = new HashSet<推薦店家>();
        }
    
        public int 分類Id { get; set; }
        public string 分類名稱 { get; set; }
    
        public virtual ICollection<推薦店家> 推薦店家 { get; set; }
    }
}
