//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTWIN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 店家登錄
    {
        public int 登錄Id { get; set; }
        public bool 是登錄店家資料 { get; set; }
        public bool 是廣告刊登 { get; set; }
        public string 店家名稱 { get; set; }
        public string 聯絡人 { get; set; }
        public string 刊登電話 { get; set; }
        public string 聯絡電話 { get; set; }
        public string Email { get; set; }
    }
}
