//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTWIN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 首頁項目分類
    {
        public 首頁項目分類()
        {
            this.首頁項目 = new HashSet<首頁項目>();
        }
    
        public int 分類Id { get; set; }
        public string 分類名稱 { get; set; }
    
        public virtual ICollection<首頁項目> 首頁項目 { get; set; }
    }
}
