//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTWIN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 首頁項目
    {
        public int 首頁項目Id { get; set; }
        public string 圖檔替代名稱 { get; set; }
        public string 圖檔提示文字 { get; set; }
        public string 圖片檔位置 { get; set; }
        public string 連結網址 { get; set; }
        public int 總曝光數 { get; set; }
        public int 總點擊次數 { get; set; }
        public string 建立者 { get; set; }
        public Nullable<System.DateTime> 建立時間 { get; set; }
        public string 修改者 { get; set; }
        public Nullable<System.DateTime> 修改時間 { get; set; }
        public bool 已刪除 { get; set; }
        public int 項目類型Id { get; set; }
    
        public virtual 首頁項目分類 首頁項目分類 { get; set; }
    }
}
